[package]
name = "inlyne"
version = "0.1.1"
description = "Introducing Inlyne, a GPU powered yet browsless tool to help you quickly view markdown files in the blink of an eye."
edition = "2021"
authors = ["trimental"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/trimental/inlyne"
homepage = "https://github.com/trimental/inlyne"

[dependencies]
pollster = "0.2.5"
wgpu_glyph =  "0.17.0"
winit = "0.26.0"
wgpu = "0.13.1"
bytemuck = "1.11.0"
lyon = "1.0.0"
comrak = "0.14.0"
open = "3.0.2"
html5ever = "0.26.0"
image = "0.24.3"
reqwest = { version = "0.11.11", features = ["blocking"] }
clap = {version = "3.2.16", features = ["derive"] }
copypasta = "0.8.1"

[profile.release]
debug = true
